services:
  - type: web
    name: portfolio
    env: python
    plan: free

    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend-react
      npm install
      npm run build

    startCommand: cd backend && gunicorn wsgi:app

    envVars:
      - key: PYTHONPATH
        value: .

    autoDeploy: true
