services:
  - type: web
    name: portfolio
    env: python
    plan: free

    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend-react
      npm install
      npm run build
      cd ..
      mkdir -p backend/app/static/dist
      cp -r frontend-react/dist/* backend/app/static/dist/

    startCommand: cd backend && gunicorn wsgi:app

    envVars:
      - key: PYTHONPATH
        value: .

    autoDeploy: true
