services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend-react && npm install && npm run build && cd ..
    startCommand: gunicorn backend.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
